# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=60)),
                ('team', models.CharField(max_length=20)),
                ('contract_type', models.CharField(max_length=20)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('signing_bonus', models.DecimalField(decimal_places=2, max_digits=5)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=5)),
                ('yr1_salary', models.DecimalField(decimal_places=2, max_digits=5)),
                ('yr2_salary', models.DecimalField(decimal_places=2, max_digits=5)),
                ('yr3_salary', models.DecimalField(decimal_places=2, max_digits=5)),
                ('yr4_salary', models.DecimalField(decimal_places=2, max_digits=5)),
                ('yr5_salary', models.DecimalField(decimal_places=2, max_digits=5)),
                ('yr1_sb', models.DecimalField(decimal_places=2, max_digits=5)),
                ('yr2_sb', models.DecimalField(decimal_places=2, max_digits=5)),
                ('yr3_sb', models.DecimalField(decimal_places=2, max_digits=5)),
                ('yr4_sb', models.DecimalField(decimal_places=2, max_digits=5)),
                ('yr5_sb', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notes', models.TextField()),
            ],
        ),
    ]
