# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyno', '0005_auto_20160102_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=60)),
                ('yearly_cost', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
