# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyno', '0006_salarylisting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('internal_name', models.CharField(max_length=20)),
                ('nickname', models.CharField(blank=True, max_length=60, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('yr1_cap_penalty', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('yr2_cap_penalty', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('yr3_cap_penalty', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('yr4_cap_penalty', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('yr5_cap_penalty', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
