# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyno', '0007_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('text_variable', models.TextField(blank=True, null=True)),
                ('int_variable', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
