# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyno', '0008_variable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('yr1_role', models.CharField(blank=True, max_length=8, null=True)),
                ('yr2_role', models.CharField(blank=True, max_length=8, null=True)),
                ('yr3_role', models.CharField(blank=True, max_length=8, null=True)),
                ('yr4_role', models.CharField(blank=True, max_length=8, null=True)),
                ('yr5_role', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
    ]
