# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyno', '0011_availablerole_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablerole',
            name='applies_to_DEF',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='availablerole',
            name='applies_to_K',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='availablerole',
            name='applies_to_QB',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='availablerole',
            name='applies_to_RB',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='availablerole',
            name='applies_to_TE',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='availablerole',
            name='applies_to_WR',
            field=models.BooleanField(default=False),
        ),
    ]
