# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyno', '0012_auto_20160104_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='yr1_role',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='yr2_role',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='yr3_role',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='yr4_role',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='yr5_role',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
