# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyno', '0013_auto_20160104_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='flex_1',
            field=models.CharField(default='WR 3', max_length=8),
        ),
        migrations.AddField(
            model_name='team',
            name='flex_2',
            field=models.CharField(default='RB 3', max_length=8),
        ),
    ]
