# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyno', '0014_auto_20160105_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablerole',
            name='unique_role',
            field=models.BooleanField(default=False),
        ),
    ]
