# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dyno', '0016_auto_20160106_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='player',
            name='variables',
        ),
    ]
