# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyno', '0018_team_team_org_view_selected'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('os', models.CharField(max_length=40)),
                ('browser', models.CharField(max_length=40)),
                ('resolution', models.CharField(max_length=40)),
                ('other_envirn', models.TextField()),
                ('report', models.TextField()),
                ('title', models.CharField(blank=True, max_length=40)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Verified', 'Verified'), ('Working', 'Working'), ('Testing', 'Testing Solution'), ('Fixed', 'Fixed'), ('Cannot Replicate', 'Cannot Replicate'), ('Unknown', 'Unknown'), ('Ignored', 'Ignored')], default='Open', max_length=40)),
                ('priority', models.IntegerField(choices=[(1, 'Urgent'), (2, 'High'), (3, 'Medium'), (4, 'Low')], default=4)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestedFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('feature', models.TextField()),
            ],
        ),
    ]
