# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyno', '0020_auto_20160113_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='yr1_balance',
            field=models.DecimalField(decimal_places=2, default=60.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='team',
            name='yr1_bonuses',
            field=models.CommaSeparatedIntegerField(default='0,0', max_length=2),
        ),
        migrations.AddField(
            model_name='team',
            name='yr2_balance',
            field=models.DecimalField(decimal_places=2, default=60.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='team',
            name='yr2_bonuses',
            field=models.CommaSeparatedIntegerField(default='0,0', max_length=2),
        ),
        migrations.AddField(
            model_name='team',
            name='yr3_balance',
            field=models.DecimalField(decimal_places=2, default=60.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='team',
            name='yr3_bonuses',
            field=models.CommaSeparatedIntegerField(default='0,0', max_length=2),
        ),
    ]
