# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyno', '0021_auto_20160114_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
