# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyno', '0022_team_current_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='yr1_bonuses',
            field=models.CommaSeparatedIntegerField(default='0,0', max_length=3),
        ),
        migrations.AlterField(
            model_name='team',
            name='yr2_bonuses',
            field=models.CommaSeparatedIntegerField(default='0,0', max_length=3),
        ),
        migrations.AlterField(
            model_name='team',
            name='yr3_bonuses',
            field=models.CommaSeparatedIntegerField(default='0,0', max_length=3),
        ),
    ]
