# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyno', '0023_auto_20160114_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='filtered_tags',
            field=models.TextField(default=''),
        ),
    ]
