from django.contrib import admin
from .models import *

admin.site.register(Player)
admin.site.register(Message)
admin.site.register(SalaryListing)
admin.site.register(Team)
admin.site.register(Variable)
admin.site.register(Role)
admin.site.register(AvailableRole)
admin.site.register(Bug)
admin.site.register(RequestedFeature)
admin.site.register(Auction)
admin.site.register(Transaction)
admin.site.register(Alert)
admin.site.register(AlertSetting)
admin.site.register(TeamVariable)
admin.site.register(ADP)
admin.site.register(Performance_Yr1)
admin.site.register(Performance_Yr2)
admin.site.register(Asset)
