from django.conf.urls import url
from . import views
from . import processing

urlpatterns = [
    url(r'^$', views.mainpage, name='main page'),
    url(r'^login$', views.loginpage, name='login'),
    url(r'^perform_login$', views.loginView, name='perform login'),
    url(r'^login_failed$', views.loginfailed, name='login failed'),
    url(r'^logout$', views.logoutView, name='logout'),
    url(r'^main$', views.mainpage, name='main page'),
    url(r'^rules$', views.rulespage, name='rules page'),
    url(r'^message_board$', views.messageboardpage, name='message board'),
    url(r'^draft$', views.draftpage, name='draft page'),
    url(r'^auction$', views.auctionpage, name='auction page'),
    url(r'^league/all_players$', views.leagueallplayerspage, name='league page - all players'),
    url(r'^league/extensions$', views.leagueextensions, name='league page - extensions'),
    url(r'^league/salary_lists$', views.leaguesalarylists, name='league page - salary lists'),
    url(r'^league/future_draft_picks$', views.leaguefuturedraftpicks, name='league page - future draft picks'),
    url(r'^league/cap_summary$', views.leaguecapsummary, name='league page - cap summary'),
    url(r'^settings$', views.settingspage, name='settings page'),
    url(r'^batch$', views.batchpage, name='batch page'),
    url(r'^process_player_contract_batch$', views.processplayercontractsbatch, name='process player contracts batch'),
    url(r'^process_salary_lists_batch$', views.processsalarylistsbatch, name='process salary lists batch'),
    url(r'^reset_all_roles$', views.resetallroles, name='reset all roles'),
    url(r'^reset_available_roles$', views.resetavailableroles, name='reset available roles'),
    url(r'^player$', views.playerpage, name='player page'),
    url(r'^player_processing_1$', processing.player_processing_1, name='player processing 1'),
    url(r'^player_processing_2$', processing.player_processing_2, name='player processing 2'),
    url(r'^player_processing_3$', processing.player_processing_3, name='player processing 3'),
    url(r'^team/organization$', views.teamorganizationpage, name='team organization page'),
    url(r'^team_org_processing_save_flex$', processing.team_org_processing_save_flex, name='team org processing - save flex change'),
    url(r'^team_org_processing_save_role_change$', processing.team_org_processing_role_change, name='team org processing - save role change'),
    url(r'^team/cap_situation$', views.teamcapsituationpage, name='team organization page'),
    url(r'^team/team_settings$', views.teamsettingspage, name='team organization page'),
    url(r'^team/release_players$', views.teamreleaseplayerspage, name='team release players page'),
    url(r'^test$', views.testview, name='testing'),
    url(r'^test_function$', processing.test_perform, name='testing performing a function'),
    url(r'^test_function2$', processing.test_perform2, name='testing performing a function #2'),
    url(r'^test_function3$', processing.test_perform3, name='testing performing a function #3'),
    url(r'^store_player_selected_redirect_to_playerpage$', processing.store_player_selected_redirect_to_playerpage, name='store player selected and redirect to player page'),
    url(r'^unload_player_selected_variable$', processing.unload_player_selected_variable, name='unload Variable player_selected'),
    url(r'^unload_team_selected_variable$', processing.unload_team_selected_variable, name='unload Variable team_selected'),
    url(r'^team_org_store_view_selected$', processing.team_org_store_view_selected, name='store which team view is selected'),
    url(r'^team/team_org_change_team_\d{1,2}$', processing.team_org_change_team_selected, name='changing which team is selected in team organization page'),
    url(r'^user_change_password$', views.user_change_password_page, name='user change username and password'),
    url(r'^verify_password_change$', processing.verify_password_change, name='verify password change'),
    url(r'^verify_username_change$', processing.verify_username_change, name='verify user change'),
    url(r'^change_team_settings$', processing.change_team_settings, name='verify user change'),
    url(r'^team_cap_save_role_change$', processing.team_cap_save_role_change, name='save role change in team cap situation page'),
    url(r'^bug_tracking$', views.bugtrackingpage, name='bug tracking page'),
    url(r'^new_bug$', views.newbugpage, name='new bug submission'),
    url(r'^save_new_bug$', processing.save_new_bug, name='save new bug submission'),
    url(r'^feature_request$', views.featurerequestpage, name='request new feature'),
    url(r'^process_feature_request$', processing.process_feature_request, name='process feature request'),
    url(r'^save_team_settings_player_filters$', processing.save_team_settings_player_filters, name='save player filter info when leaving team settings'),
]